# Generated by Django 2.1.5 on 2022-01-24 02:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0002_documento_pertece'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='pertece',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='funcionarios.Funcionario'),
            preserve_default=False,
        ),
    ]
