# Generated by Django 2.1.5 on 2022-01-30 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documentos', '0004_documento_arquivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='pertece',
            new_name='pertence',
        ),
    ]
